#!/usr/bin/env bash

TARGET_DIR="/home/alexandrawinsnes/Downloads"


    # Creating directories
mkdir -p "$TARGET_DIR"/{Docs,Images,Music,Other,PDF,Script,Text}

    # Creating files
touch "$TARGET_DIR"/{a,b,c}.txt "$TARGET_DIR"/cool{1..5}.pdf "$TARGET_DIR"/awesome_{1..4}.mp4 "$TARGET_DIR"/beautiful.jpg "$TARGET_DIR"/coolu.png "$TARGET_DIR"/notes.docx "$TARGET_DIR"/notes.sh "$TARGET_DIR"/pretty{1..3}.mp3

    # Moving my files in to correct the directories
mv "$TARGET_DIR"/{a,b,c}.txt "$TARGET_DIR"/Text
mv "$TARGET_DIR"/cool{1..5}.pdf "$TARGET_DIR"/PDF
mv "$TARGET_DIR"/awesome_{1..4}.mp4 "$TARGET_DIR"/Other
mv "$TARGET_DIR"/coolu.png "$TARGET_DIR"/Images
mv "$TARGET_DIR"/notes.docx "$TARGET_DIR"/Docs
mv "$TARGET_DIR"/notes.sh "$TARGET_DIR"/Script
mv "$TARGET_DIR"/pretty{1..3}.mp3 "$TARGET_DIR"/Music
mv "$TARGET_DIR"/beautiful.jpg "$TARGET_DIR"/Images

    # Automatically sorting files in to the correct directories
inotifywait -m -e create,moved_to --format '%w%f' "$TARGET_DIR" |
while read file 
do
     case "$file" in

        *.pdf)
            mv "$file" "$TARGET_DIR/PDF/" ;;
        *.jpg|*.png)
            mv "$file" "$TARGET_DIR/Images/" ;;
        *.mp3)
            mv "$file" "$TARGET_DIR/Music/" ;;
        *.mp4)
            mv "$file" "$TARGET_DIR/Other/" ;;
        *.txt)
            mv "$file" "$TARGET_DIR/Text/" ;;
        *.docx)
            mv "$file" "$TARGET_DIR/Docs/" ;;
        *.sh)
            mv "$file" "$TARGET_DIR/Script/" ;;

    esac

done
